# -*- coding: utf-8 -*-
"""1. middle_letter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp3Q2MUqSpII8VXj__HOCDEN56ZX6nvg
"""

# -*- coding: utf-8 -*-
"""
Project: Middle Letter Finder
Description:
Removes any accidental leading/trailing spaces from user input,
checks that the input is not empty and contains only alphabetic characters,
then prints the middle character(s) of the word.
Author: Katsiaryna Kavaleuskaya
"""

# Remove accidental spaces at the beginning or end of the word
latin_word = input('Enter a word: ').strip()

# Check that the input is not empty
if len(latin_word) == 0:
    print("Input is empty.")
# Check that the input contains only alphabetic characters
elif not latin_word.isalpha():
    print("Invalid input: must contain only alphabetic characters.")
else:
    word_length = len(latin_word)
    middle_index = word_length // 2
    # If the length is odd — print one middle character; if even — print two
    if word_length % 2 != 0:
        print(latin_word[middle_index])
    else:
        print(latin_word[middle_index - 1 : middle_index + 1])