# -*- coding: utf-8 -*-
"""2. sum_until_zero

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4SKKTZmzcxeMO4tFvWP0va7BjGKFEgu
"""

# -*- coding: utf-8 -*-
"""
Project: Sum Until Zero
Description:
The program repeatedly prompts the user to enter numbers one by one.
It stops when the user enters zero,
and then prints the sum of all previously entered numbers.
Robust input: non-numeric and empty values are handled safely.
Author: Katsiaryna Kavaleuskaya
"""

# #SafeInput — the program will not crash on text or empty input

total = 0

# Using float to allow both integers and decimal numbers.
while True:
    # Safe input loop
    while True:
        s = input('Enter a number: ').strip()
        try:
            user_input = float(s)
            break
        except ValueError:
            print('Error! Please enter a number.')

    if user_input == 0:
        break
    total += user_input

print('Result:', total)