# -*- coding: utf-8 -*-
"""4_avg_temp_per_country

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX4SvqTKo4Jtt8X0EFmC_0bAjToBP_s9
"""

# -*- coding: utf-8 -*-
"""
Task 4: Calculate average temperature per country in Celsius.

Given a list of average daily temperatures in Fahrenheit for different countries
and periods, write code that calculates the average temperature in Celsius (!)
for each country.

Example:

countries_temperature = [
    ['Thailand', [75.2, 77, 78.8, 73.4, 68, 75.2, 77]],
    ['Germany', [57.2, 55.4, 59, 59, 53.6]],
    ['Russia', [35.6, 37.4, 39.2, 41, 42.8, 39.2, 35.6]],
    ['Poland', [50, 50, 53.6, 57.2, 55.4, 55.4]]
]

Expected output:
Average temperature per country:
Thailand  -  23.9 C
Germany   -  13.8 C
Russia    -   3.7 C
Poland    -  12.0 C
"""

countries_temperature = [
    ['Thailand', [75.2, 77, 78.8, 73.4, 68, 75.2, 77]],
    ['Germany', [57.2, 55.4, 59, 59, 53.6]],
    ['Russia', [35.6, 37.4, 39.2, 41, 42.8, 39.2, 35.6]],
    ['Poland', [50, 50, 53.6, 57.2, 55.4, 55.4]]
]

# Function to convert Fahrenheit to Celsius
def fahrenheit_to_celsius(f):
    return (f - 32) * 5 / 9

print('Average temperature per country:')
for country_data in countries_temperature:
    country_name = country_data[0]          # Country name
    temps_fahrenheit = country_data[1]      # List of temperatures in Fahrenheit
    # Convert all temperatures to Celsius
    temps_celsius = [fahrenheit_to_celsius(f) for f in temps_fahrenheit]
    # Calculate the average temperature in Celsius
    avg_temp_celsius = sum(temps_celsius) / len(temps_celsius)
    print(f'{country_name}  -  {avg_temp_celsius:.1f} C')