# -*- coding: utf-8 -*-
"""Functions_homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFYWMZHSliFd-oYzRhFCzvNvuUiZ8SOd
"""

"""
Document Management System.

A console program to automate secretary tasks of managing documents.
Allows performing search, add, delete, and move document operations.
"""

from typing import List, Dict, Tuple, Optional, Generator, Callable

# Initial data
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

# ========== HELPER FUNCTIONS ==========
# ... (full code from your functions_homework.py here)
